### ISSUE TITLE
WindowsError: [Error 87] when trying to run a new job.

### ISSUE THREAD

**Issue by callym** [fsiddi/flamenco#125]
I have followed the guide in the readme on how to run flamenco, and it all seems to be working okay, the Blender plugin adds jobs to the web interface, but when the worker tries to run them, I get this error:

```
Worker Loop
Registering
Quering for a new task
New Task Found 1, job 1
Fetching job file 1
Extracting c:\users\callum\appdata\local\temp\flamenco-worker\1\taskfile_1.zip
Fetching support file 1
Extracting c:\users\callum\appdata\local\temp\flamenco-worker\1\tasksupportfile_
1.zip
Fetching deppend file http://localhost:7777/static/storage/1/dependencies_1.zip
Extracting c:\users\callum\appdata\local\temp\flamenco-worker\1\dependencies.zip

Removing bad zipfile c:\users\callum\appdata\local\temp\flamenco-worker\1\depend
encies.zip
ERROR:root:Not a ZipFile
200
Running:

-noaudio
--background
c:\users\callum\appdata\local\temp\flamenco-worker\1\1\\testflamenco.blend
--render-output
c:\users\callum\appdata\local\temp\flamenco-worker\1\output\1\####
--python
c:\users\callum\appdata\local\temp\flamenco-worker\1\1\\pre_render.py
--frame-start
1
--frame-end
1
--render-format
PNG
--render-anim
--enable-autoexec
Traceback (most recent call last):
  File "manage.py", line 63, in <module>
    manager.run()
  File "C:\Python27\lib\site-packages\flask_script\__init__.py", line 412, in ru
n
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "C:\Python27\lib\site-packages\flask_script\__init__.py", line 383, in ha
ndle
    res = handle(*args, **config)
  File "C:\Python27\lib\site-packages\flask_script\commands.py", line 216, in __
call__
    return self.run(*args, **kwargs)
  File "manage.py", line 48, in runserver
    controllers.worker_loop()
  File "C:\Users\Callum\Desktop\flamenco-2.0.0-beta.1\flamenco\worker\applicatio
n\controllers.py", line 225, in worker_loop
    execute_task(task, files)
  File "C:\Users\Callum\Desktop\flamenco-2.0.0-beta.1\flamenco\worker\applicatio
n\controllers.py", line 655, in execute_task
    run_blender_in_thread(options)
  File "C:\Users\Callum\Desktop\flamenco-2.0.0-beta.1\flamenco\worker\applicatio
n\controllers.py", line 477, in run_blender_in_thread
    stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 87] The parameter is incorrect
```

This is with the default Blender cube scene, BAM 0.0.4.4, Windows 8.1 x64

I originally thought that it could be because I have Blender installed on my desktop, but adding the path to the server settings page, or to the manager\application\config.py BLENDER_PATH_WIN config doesn't seem to change anything.

**Comment by EVMosaic** [comment]
Have also had this problem on Windows. Identical when starting jobs from within Blender or in the Dashboard.

**Comment by Eibriel** [comment]
Looks like the Blender path is not set.
The Manager should ask for it when you start it for the first time.
¿Do you set it?
You can force the Manager to ask you again deleting the manager database (manager.sqlite or task_queue.sqlite).

If you are ok tweaking the database take a look to [this comment](https://github.com/fsiddi/flamenco/issues/119#issuecomment-83987488).

**Comment by callym** [comment]
Thanks! That fixed it! I thought adding it to the manager config.py had set it.

What am I meant to do when running this on multiple computers? I assumed that I would just run the Worker script on the other ones, leaving one computer as the manager, but what if these other computers have Blender in a different location? Is each computer meant to be its own worker and manager?

**Comment by Eibriel** [comment]
Sorry about that, the config.py paths are old code that need to be cleaned up.

Normally in a renderfarm every node has the same configuration, and blender is located in the same path. Currently is no way to set the blender path on each Worker, if you are coder you are welcomed to add that option! should be easy. The path is set [here in the code](https://github.com/fsiddi/flamenco/blob/1433531723a66198f7318fdeda5e02e9fef37af2/flamenco/worker/application/controllers.py#L490).

So, it is working on Windows? Please confirm! Is kind a miracle, because was never tested on that platform :laughing:

**Comment by callym** [comment]
It seems to be working. I had some bugs where it was just rendering the default cube, but either restarting Blender or restarting Flamenco seems to have fixed it.

I can send tasks from blender on one computer to be rendered on another one, which is great! What's quite annoying is that deleting jobs from the web gui doesn't seem to actually be deleting them, so I end up with loads of job folders to sort through. Also what would be nice would be being able to download the output straight from the web gui, as the less time I have to spend transferring files from one system to another, the better!

Also it would be nice if you could put in the Flamenco server URL from the Blender panel, instead of inside the addons screen. Also the "Start Job" checkbox doesn't seem to do anything, the job is automatically started whether I click it or not.

It also doesn't seem to be working with LuxRender, just rendering a blank grey rectangle, but I'm not sure whether this is a Windows error or just a general error, but it's pretty odd, I assumed you were running Blender from the command line and taking the output image from that, are you not?

**Comment by callym** [comment]
Odd, it seems to be working with LuxRender now, but I've got another issue where sometimes the name of the .blend file in the server storage jobfile_x.zip doesn't match up with the one in the temp flamenco-worker taskfile_x.zip, so the worker tries to open the blend with the name from the jobfile, and fails because it doesn't match up with the taskfile. 

I can't seem to reproduce it, I just tried to but now it seems to be working again!

**Comment by EVMosaic** [comment]
So I redid the configuration and I'm no longer getting that error, I have however been unable to get it to work. It is now failing with the following readout.

Worker Loop
Registering
Quering for a new task
New Task Found 1, job 1
Fetching job file 1
Extracting c:\users\ericva~1\appdata\local\temp\flamenco-worker\1\taskfile_1.zip
Fetching support file 1
Extracting c:\users\ericva~1\appdata\local\temp\flamenco-worker\1\tasksupportfile_1.zip
Fetching deppend file http://localhost:7777/static/storage/1/dependencies_1.zip
Extracting c:\users\ericva~1\appdata\local\temp\flamenco-worker\1\dependencies.zip
Removing bad zipfile c:\users\ericva~1\appdata\local\temp\flamenco-worker\1\dependencies.zip
ERROR:root:Not a ZipFile
200
Running:
C:\Program Files\Blender Foundation\Blender
-noaudio
--background
c:\users\ericva~1\appdata\local\temp\flamenco-worker\1\1\\Ftest.blend
--render-output
c:\users\ericva~1\appdata\local\temp\flamenco-worker\1\output\1\####
--python
c:\users\ericva~1\appdata\local\temp\flamenco-worker\1\1\\pre_render.py
--frame-start
1
--frame-end
5
--render-format
PNG
--render-anim
--enable-autoexec
Traceback (most recent call last):
  File "E:\git\flamencobeta\flamenco\flamenco\worker\manage.py", line 63, in <module>
    manager.run()
  File "C:\Python27\lib\site-packages\flask_script\__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "C:\Python27\lib\site-packages\flask_script\__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "C:\Python27\lib\site-packages\flask_script\commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "E:\git\flamencobeta\flamenco\flamenco\worker\manage.py", line 48, in runserver
    controllers.worker_loop()
  File "E:\git\flamencobeta\flamenco\flamenco\worker\application\controllers.py", line 225, in worker_loop
    execute_task(task, files)
  File "E:\git\flamencobeta\flamenco\flamenco\worker\application\controllers.py", line 655, in execute_task
    run_blender_in_thread(options)
  File "E:\git\flamencobeta\flamenco\flamenco\worker\application\controllers.py", line 477, in run_blender_in_thread
    stderr=subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 5] Access is denied
(flamenco_venv) PS E:\git\flamencobeta\flamenco\flamenco\worker>

The best google can tell me is to run the terminal windows as administrator but even with doing this I have been unsuccessful so far.

**Comment by Eibriel** [comment]
Hi @EVMosaic , you need the path to blender, no to blender folder:
```
C:\Program Files\Blender Foundation\Blender\blender
```
Instead of:
```
C:\Program Files\Blender Foundation\Blender
```

**Comment by Eibriel** [comment]
Hi @callym if you get an error about .zip is OK, is just a warning (I should change the text).

I've no tested Flamenco with Luxrender, should work, except for the Thumbnails

The number on taskfile and jobfile should be different, that is OK
