### ISSUE TITLE
Only one worker working at a time?

### ISSUE THREAD

**Issue by callym** [fsiddi/flamenco#128]
I've managed to get the system running on Windows, the dashboard shows my two workers, but I can see from the logs that when I send a file from the Blender addon to be rendered, one worker is being given all the frames to render, and the other one sits there doing nothing.

Both workers are connected to the same manager. 

I assumed that the manager would send frames to the workers as they finish them, so all the workers are currently working, is this not how it's meant to work?

**Comment by Eibriel** [comment]
Every worker renders 5 frames, if your animation is shorten than that will be rendered only on one worker

**Comment by Eibriel** [comment]
The chunk size is configurable

**Comment by callym** [comment]
Yep, that works great, thanks!
