### ISSUE TITLE
input path server settings disappeared.

### ISSUE THREAD

**Issue by antonvdh** [fsiddi/flamenco#129]
when I type in the path server settings and click on update the input text disappeared.
Also with project path and new job so I cannot choose anything to make a new job.

**Comment by Eibriel** [comment]
Hi @antonvdh , yes, that part of the Dashboard is unfinished. You should use the blender Addon to submit Jobs, you can find the addon on the "Plugins" folder

**Comment by antonvdh** [comment]
Plugin cannot connect wrong ip server number.
How to change that in the blender plugin?

**Comment by antonvdh** [comment]
Sorry for the late response I could simply set the server url in blender user preferences.
Works awesome.

**Comment by antonvdh** [comment]
Would be nice if I could test beta1 still working with the alpha release.
Dashboard server settings not working.

**Comment by antonvdh** [comment]
Made the settings with SQlite management problem solved.
